CREATE TABLE genres(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    name TEXT NOT NULL
);

"""
Creating movie_genres table
"""
CREATE TABLE movie_genres (
    movie_id INT REFERENCES movies(id) ON DELETE CASCADE, 
    genre_id INT REFERENCES genres(id) ON DELETE CASCADE,
	main BOOLEAN NOT NULL,
	PRIMARY KEY(movie_id, genre_id, main)
);

CREATE TABLE people(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    surname TEXT,
    first_name TEXT
);

CREATE TABLE movies(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    title TEXT NOT NULL,
    year INT,
    rating NUMERIC(2,1),
    runtime INT, 
    main_genre TEXT
);

CREATE TABLE movie_genres(
    movie_id INT REFERENCES movies(id) ON DELETE CASCADE, 
    genre_id INT REFERENCES genres(id) ON DELETE CASCADE
);

CREATE TABLE movie_personnel(
    movie_id INT REFERENCES movies(id) ON DELETE CASCADE, 
    person_id INT REFERENCES people(id) ON DELETE CASCADE,
    role TEXT
);

CREATE TABLE temp(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    title TEXT NOT NULL,
    year INT,
    director TEXT,
    actors TEXT,
    rating NUMERIC(2,1),
    runtime INT, 
    main_genre TEXT,
    side_genre TEXT
);